{application,straw_hat_mailer,
             [{applications,[kernel,stdlib,elixir,logger,swoosh,gen_smtp,
                             postgrex,ecto,scrivener_ecto]},
              {description,"  Mailer Management\n"},
              {modules,['Elixir.StrawHat.Mailer',
                        'Elixir.StrawHat.Mailer.Application',
                        'Elixir.StrawHat.Mailer.Email',
                        'Elixir.StrawHat.Mailer.Mailer',
                        'Elixir.StrawHat.Mailer.Repo',
                        'Elixir.StrawHat.Mailer.Schema.Template',
                        'Elixir.StrawHat.Mailer.Schema.Template.From',
                        'Elixir.StrawHat.Mailer.Template']},
              {registered,[]},
              {vsn,"0.0.1"},
              {mod,{'Elixir.StrawHat.Mailer.Application',[]}},
              {extra_applications,[logger,swoosh,gen_smtp]}]}.
